export const HOS_CONSTANTS = {
  MAX_DRIVING_HOURS: 11,
  MAX_14_HOUR_WINDOW: 14,
  MIN_OFF_DUTY_HOURS: 10,
  MAX_CYCLE_HOURS: 70,
  CYCLE_DAYS: 8,
  REQUIRED_BREAK_MINUTES: 30,
  BREAK_REQUIRED_AFTER_HOURS: 8,
  FUEL_STOP_INTERVAL_MILES: 1000,
  PICKUP_DROPOFF_DURATION_HOURS: 1,
  AVERAGE_SPEED_MPH: 60
}

